### ISSUE TITLE
Language selector shows incorrect language.

### ISSUE THREAD

**Issue by GrunowIT** [Kentico/training-kentico-k12#27] opened 2019-03-15 13:53 UTC
### Brief bug description

Language selector shows incorrect language.

### Repro steps

1. Make sure you browse the MedioClinic page on English.
1. Go to 'Contact Us'
2. Click on the language selector
3. Select spanish
4. You get a 404 page, because 'Contact Us' does not exist in spanish
5. Read the language letter on the language selector. (DE for me, but there is no German setup in Kentico)

### Expected behavior

The language selector properly shows "EN".

### Test environment

 - Platform/OS: Windows 10, Default vanilla installation of the Demo
 - Browser Chrome
 - Commit 827abeb4a5465890b1b72fd1b516779fffdba34b

### Screenshots

![image](https://user-images.githubusercontent.com/6489836/54436042-194e2780-4732-11e9-9054-0c3b3a6d9682.png)

**Comment by JanLenoch** [comment] 2019-03-18 11:17
Hi @GrunowIT , thanks for letting us know! We'll take a look at it.

**Comment by JanLenoch** [comment] 2019-03-21 11:40
Hi @GrunowIT , I can't seem to be able to reproduce the behavior.

Are you sure you have both the code and the database in the state of https://github.com/Kentico/training-kentico-k12/commit/827abeb4a5465890b1b72fd1b516779fffdba34b ?

The language selector is built in the `_Layout.cshtml` file using DTOs factored out of `CultureSiteInfo` objects. The UI culture that the layout uses to pick the right culture abbreviation is being set by the route handler applied in `RouteConfig.cs`. However, the `NotFound` route is cultureless. Therefore, the default culture is displayed, no matter of the culture of the referrer's request. I suspect you might have had the German culture accidentally set in the `defaultCulture` variable in `RouteConfig.cs`. Wasn't that the case?

Thanks.

**Comment by JanLenoch** [comment] 2019-04-09 08:57
Hi @GrunowIT , as I couldn't reproduce the behavior, I'll close this one. Feel free to let me know if you want to re-open it.

Jan

**Closed by JanLenoch** 2019-04-09 08:57 UTC
